[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
pumpfun = "5FMQj6GpqSTFoRSzqP6d1P2Um4YLbzSvyJibuUusVs6Q"

[registry]
url = "https://api.mainnet.solana.com"

[provider]
cluster = "mainnet"
wallet = "/Users/atrey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
